# Generated by Django 5.2.7 on 2025-11-05 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='semester',
            field=models.ManyToManyField(blank=True, to='dashboard.semester'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='teacher',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='dashboard.teacher'),
        ),
    ]
