# Generated by Django 5.2.7 on 2025-11-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_marks_student_alter_marks_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='course',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
