# Generated by Django 5.2.7 on 2025-11-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_marks_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='student',
            field=models.IntegerField(),
        ),
    ]
